### ISSUE TITLE
No module named 'top_pool'

### ISSUE THREAD

**Issue by THEFASHIONGEEK** [Tessellate-Imaging/Monk_Object_Detection#11]
I am running CornerNet-lite Example in colab. While running 
`from train_detector import Detector`  I got this error

![image](https://user-images.githubusercontent.com/50513357/76204910-45a26400-621f-11ea-9c01-989eea0ca9ac.png)

**Comment by abhi-kumar** [comment]
That error is because you might be using a certain older version of  monk object detection. It happened because the older version had precompiled binary (.so) files from my system pushed into the commit, which restricted the re-compiling of the binaries as per your system configurations.

Please clone the library again and reinstall as per the instructions.

If the error still persists, drop a comment here.

Happy coding!!

**Comment by THEFASHIONGEEK** [comment]
I have cloned the latest version itself. But, I still get the same error.

**Comment by abhi-kumar** [comment]
If you are running it on colab, follow these steps,

#clone library
! git clone https://github.com/Tessellate-Imaging/Monk_Object_Detection.git

#install 
cd Monk_Object_Detection/6_cornernet_lite/installation
! chmod +x install.sh
! ./install.sh


# move back to root dir
cd ../../../
# this should take you back to /content


#Very important, reset the runtime (using "Runtime" drop down menu in tool bar)

# import
import os
import sys
sys.path.append("Monk_Object_Detection/6_cornernet_lite/lib/")
from train_detector import Detector

**Comment by abhi-kumar** [comment]
Closing the issue.
